### ISSUE TITLE
Long log messages permanently increase heap size

### ISSUE THREAD

**Issue by jabersmith** [kentik/golog#13]
golog's logger_writer component works by allocating a fixed set of bytes.Buffer objects at startup, and reusing them throughout the lifetime of a service.  So a log message is written into the Buffer, the Buffer is sent to a channel, the log-writer goroutine reads it from the channel, writes its contents to stdout/syslog/wherever, and then the buffer is Reset() and sent to another channel to await reuse.

But bytes.Buffer.Reset, as documented, 
> resets the buffer to be empty, but it retains the underlying storage for use by future writes.

This means that, if we ever log an extremely long line, like a megabyte-long query-text at either runner-master or runner-worker, we will *never* release the megabyte of memory we allocated to store it, even though it won't normally be used by future log messages that reuse the buffer.  golog retains 10,240 of these message buffers, and runner-master currently enforces a limit of 2MB on the text of an individual query, so it's possible for a single instance of runner-master or -worker to retain up to 20GB of heap space after a period of long queries.  (runner-master logs the full query text of every query it runs; runner-worker logs them only on timeouts, but in many cases, these extremely-long queries are exactly the ones most likely to time out.)

We should probably work in the query services to limit the amount of logging we do of these long queries, without actually reducing our visibility of when/how they occur.  But we should definitely find a way to release memory in the logging system when one of these queries is completed.

**Comment by cleroux** [comment]
Also note that the buffer is grown exponentially even if you only need a few extra bytes, the buffer's capacity will double.
https://github.com/golang/go/blob/master/src/bytes/buffer.go#L142

**Comment by cleroux** [comment]
Here's my suggestion to allow logging long messages but reclaim the memory:
```go
const reclaimThreshold int = 16384 // TODO: What's the 90th-ish? percentile for the length of our log messages?

// freeMsg releases the message back to be reused
func freeMsg(msg *logMessage) (err error) {
	if msg.Buffer.Cap() > reclaimThreshold {
		msg.Buffer = *bytes.NewBuffer(make([]byte, 0, reclaimThreshold))
	} else {
		msg.Reset()
	}
	select {
	case freeMessages <- msg: // no-op
	default:
		atomic.AddUint64(&errCount, 1)
		return ErrFreeMessageOverflow
	}

	return
}
```

**Comment by jabersmith** [comment]
Yes, that's kind of what I was thinking.  (I think you could even overwrite the buffer with just `msg.Buffer = bytes.Buffer{}`.)

I'm trying to build a little testcase to reproduce the issue, and then we can plug this in.

**Comment by cleroux** [comment]
As you mentioned, golog keeps 10,240 buffers. (https://github.com/kentik/golog/blob/master/logger/logger_writer.go#L30)

I was wondering why we need this many.  The only reason I can think of is for concurrency.  But do we reasonably expect to be producing up to 10k log messages concurrently?  I see this number was originally in the cloudflare repo that we forked. (https://github.com/cloudflare/golog/blob/master/logger/logger_writer.go#L24)  It kinda makes sense to me that cloudflare might be operating at a scale that requires 10k buffers.  But does that number make sense for us too?  Can we just hold fewer buffers?

**Comment by jabersmith** [comment]
Sorry -- lost track of this.

Totally a fair question.  I have *no* idea what typical backlogs on this channel look like.  It's hard to imagine 10,000 lines piling up without at least one of:
 - there being some logging from a fairly tight loop that probably isn't useful
 - pretty terribly slow I/O somewhere on the host (I think that for our internal services, logs are always flowing from service's stdout -> containerd -> the /data ZFS volume)

If we were concerned about *typical* memory consumption of golog, I think it would be fairly easy to remove the pre-allocation of logMessages, create them on-demand but still reuse the ones we've created using the freeMessages channel, and then have to carry no more than the actual highwater number of logMessages.  Maybe you could even do some smart adaptive freeing of the logMessages after a spike in usage.  But unless the log messages occasionally get quite large, you're still talking relatively small amounts of memory -- even in the smallest chfclient I can find on current prod, the logger is consuming only ~5% of memory:
![Screen Shot 2022-03-31 at 5 02 35 PM](https://user-images.githubusercontent.com/13960807/161169447-6d9f575d-4708-4af4-b58d-83a9d2f376b1.png)
So there's a limit to how much we can improve the overall system by shrinking the logger's minimum memory size.  But it's worth thinking about.

**Comment by jabersmith** [comment]
Anyway, I think we ought to declare victory here, and leave that new issue to track further optimizations.
